name: Deploy to remote server
on:
  push:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run git pull on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.USERNAME_SERVER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ./update_helper_5_letters_bot
